# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: materialx.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'materialx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmaterialx.proto\"6\n\x07Version\x12\r\n\x05major\x18\x01 \x01(\r\x12\r\n\x05minor\x18\x02 \x01(\r\x12\r\n\x05patch\x18\x03 \x01(\r\"\'\n\tAttribute\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"s\n\x10MaterialXElement\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x1e\n\nattributes\x18\x03 \x03(\x0b\x32\n.Attribute\x12#\n\x08\x63hildren\x18\x04 \x03(\x0b\x32\x11.MaterialXElement\"z\n\x11MaterialXDocument\x12 \n\x0eschema_version\x18\x01 \x01(\x0b\x32\x08.Version\x12\x1e\n\nattributes\x18\x02 \x03(\x0b\x32\n.Attribute\x12#\n\x08\x65lements\x18\x03 \x03(\x0b\x32\x11.MaterialXElementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'materialx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSION']._serialized_start=19
  _globals['_VERSION']._serialized_end=73
  _globals['_ATTRIBUTE']._serialized_start=75
  _globals['_ATTRIBUTE']._serialized_end=114
  _globals['_MATERIALXELEMENT']._serialized_start=116
  _globals['_MATERIALXELEMENT']._serialized_end=231
  _globals['_MATERIALXDOCUMENT']._serialized_start=233
  _globals['_MATERIALXDOCUMENT']._serialized_end=355
# @@protoc_insertion_point(module_scope)
